// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package sqlc

import (
	"database/sql"
)

type Campaign struct {
	ID     string
	Image  string
	Cta    string
	Status string
}

type TargetingRule struct {
	ID               int32
	CampaignID       sql.NullString
	IncludeCountries []string
	ExcludeCountries []string
	IncludeOs        []string
	ExcludeOs        []string
	IncludeApps      []string
	ExcludeApps      []string
}
